import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Board from "~/common/components/Board/Board";

const Home: NextPage = () => {

  /**
   * Player x
   * Player o
   */
  const [currentPlayer, setCurrentPlayer] = useState("x");

  /**
   * [
   *  [] => player x
   *  [] => player o
   * ]
   */
  const [playerMoves, setPlayerMoves] = useState<[number[], number[]]>([[], []]);

  const tiles = [
    1, 2, 3,
    4, 5, 6,
    7, 8, 9
  ];

  const combinations = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [1, 4, 7],
    [2, 5, 8],
    [1, 5, 9],
    [3, 5, 7],
  ]

  useEffect(() => {
    /** Calculate Winner */
    // playerMoves.forEach((moves, index) => {
    //   moves.forEach(move => {
        
    //   })
    })
    console.log(playerMoves)
  }, [playerMoves]);
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Tic Tac Toe
          </h1>
          <div>
            <h2 className="text-white text-lg uppercase font-extrabold"> Player Turn: <span className="uppercase text-red-500"> {currentPlayer}</span> </h2>
          </div>
          <Board
            tiles={tiles}
            currentPlayer={currentPlayer}
            setCurrentPlayer={setCurrentPlayer}
            playerMoves={playerMoves}
            setPlayerMoves={setPlayerMoves}
          />
          <button className="bg-white/10 px-4 py-2 text-white text-lg uppercase font-extrabold" onClick={() => {
            setPlayerMoves([[], []]);
            setCurrentPlayer("x")
          }}> Reset </button>
        </div>
      </main>
    </>
  );
};

export default Home;
